# Generated by Django 4.1.5 on 2023-02-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_brand_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField()),
                ("image", models.ImageField(upload_to="media")),
                ("description", models.TextField()),
                ("specification", models.TextField()),
                ("slug", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=50,
                    ),
                ),
                (
                    "labels",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("hot", "hot"),
                            ("sale", "sale"),
                            ("", "default"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.category"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.subcategory",
                    ),
                ),
            ],
        ),
    ]
